src/atoms/gv-autocomplete.js
=> fix(portal): reinit options list when input is empty

src/molecules/gv-identity-picture.js
=> fix(portal): prevent gv-image to be rendered if no picture

src/molecules/gv-table.js
=> fix: Errors when selecting a filter on an empty user agent

src/molecules/gv-table.js
=> fix(ui-components): allow to force skeleton mode on gv-table

src/atoms/gv-tag.js
=> fix(ui-components): words in gv-tag should never be broken

src/molecules/gv-code.js, stories/molecules/gv-code.stories.js, stories/molecules/gv-code.test.js
As codemirror uses 'javascript' mode to render json, gv-code now converts 'json' to 'javascript'
Fixes gravitee-io/issues#4048
=> fix(components): gv-code should accept 'json' mode for codemirror

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-file-upload.js
Add a trash icon when gv-upload is initialize with a value. It is used to delete an existing picture from an object.
Closes gravitee-io/issues#4316
=> feat(pictures): delete image

src/molecules/gv-table.js
fixes gravitee-io/issues#4035
fixes gravitee-io/issues#4461
=> fix(ui-components): a gv-tag in gv-table cell must not have width: 100%

stories/molecules/gv-table.stories.js
We have an error when consulting documentation for gv-table in storybook which prevent to load the full page.
You can test the bug here: https://components.gravitee.io/?path=/docs/molecules-gv-table--dynamic-rows
=> fix: fix error for gv-table documentation

src/atoms/gv-autocomplete.js
=> fix(gv-autocomplete): do not show no-option slot if no search is done

src/charts/gv-chart-gauge.js, stories/charts/gv-chart-gauge.stories.js
Gauges have white background. So adding them to a page with a different background color will cause a white rectangle to appear around the gauge
Gauges should have a transparent background
=> fix(gv-gauge): make background transparent

src/molecules/gv-cron-editor.js, stories/molecules/gv-cron-editor.stories.js
**Issue**
Closes https://github.com/gravitee-io/issues/issues/5039
Multiple enhancements after the integration in the healthcheck page of APIM:
- Use `autofocus` property instead of hardcoded one
- Fix some alignments and split rules/examples of pro mode in 2 verticals blocks
- Keep editor value when switching from any mode to `pro` mode
- Add a simple algo to parse the input value, if defined, and select the correct mode accordingly. It works only for `seconds`, `minutes` and `hourly`
- Set default value to 1 instead of 0 for `seconds`, `minutes` and `hourly` modes
**Screenshots**
=> Cron Editor: Various small enhancements of design and behavior

src/molecules/gv-cron-editor.js, stories/molecules/gv-cron-editor.stories.js
**Issue**
Related to https://github.com/gravitee-io/issues/issues/5039
Compute mode from the input value only for a few specific cases
To avoid ending weird states we now set the state automatically only with input value matching something like:
- `1 3 */25 * * *`
- or `2 */25 * * * *`
- or `*/25 * * * * *`
**Screenshot**
=> fix(gv-cron-editor): compute mode from the value only for a few specific cases

src/atoms/gv-link.js, src/molecules/gv-nav.js, stories/organisms/gv-user-menu.stories.js, stories/organisms/gv-vertical-menu.stories.js
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/313
I rework a bit the `gv-link` to fix an issue when using it in `gv-user-menu` with long text, see screenshots, so the text is now cropped and `...` is added when it is too long to fit. It doesn't look to break gv-link but it may be worth to check the other components you think they can be impacted.
**Screenshots**
Before:
After:
=> fix(gv-link): crop text and add `...` when it is too long to fit

src/lib/i18n.js
=> fix(i18): use relative url to load default translation

src/charts/gv-chart-bar.js, src/index.js, src/mixins/with-skeleton-attribute.js, stories/charts/gv-chart-bar.stories.js, wc/gv-chart-bar.js
Fixes https://github.com/gravitee-io/issues/issues/4892
- Creation of gv-chart-bar component
- Improvment of `withSkeletonAttribute`
=> feat: dashboard of all alerts

stories/lib/make-story.js
**Issue**
NA
Previously there was a hack to do ?a thing?.
But, as of Storybook 6.2 it looks like this hack is making some story fails, for instance, the `gv-autocomplete` ones.
So I just removed it.
Notes: In the Storybook 6.2 upgrade PR (https://github.com/gravitee-io/gravitee-ui-components/pull/317) all the CI checks were green even if we "lost" the `gv-autocomplete` stories, including Chromatic. It seems to be a strange behaviour for Chromatic because new stories are reported as new and should be accepted manually whereas deleted stories don't trigger anything. 
I will contact @chromaui foxes to check is it's the intended behaviour or if we can do something on our side to prevent that.
=> chore: remove hack on Storybook Preview block

src/atoms/gv-select.js
**Issue**
This reverts commit 1494ce05 merged with PR https://github.com/gravitee-io/gravitee-ui-components/pull/302.
The fix done in 1494ce05 is causing some issues on screens with a `gv-select` and a scrollbar, the options aren't scrolled with the rest of the page:
=> Revert "fix(gv-select): let select go out of parent item"

src/charts/gv-chart-histogram.js, src/index.js, stories/charts/gv-chart-histogram.stories.js, wc/gv-chart-histogram.js
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/489
This chart is needed to display the nodes availability like on APIM. For the moment I kept this component as simple as I can. Everything is not configurable. Feel free to tell me if you would like to make something configurable.
Here what we have on apim
Here is the new component
=> feat(gv-chart-histogram): add new component

src/charts/gv-chart-histogram.js, stories/charts/gv-chart-histogram.stories.js
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/489
Here what we had before
Here is what we have now:
=> feat(gv-chart-histogram): improve histogram chart options usage

package-lock.json, package.json, src/charts/gv-chart-bar.js, src/charts/gv-chart-gauge.js, src/charts/gv-chart-histogram.js, src/charts/gv-chart-line.js, src/charts/gv-chart-map.js, src/charts/gv-chart-pie.js, src/policy-studio/gv-policy-studio.js
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/299
I moved `asciidoctor`, `asciidoctor-highlight.js`, `highlight`, `highchart` and `@highcharts/map-collection` to peer dependencies.
This has been done in order to:
- ensure we are using the version from user's project and avoid having duplicated versions
- reduce the size of this package by making these dependencies optional peer dependencies. And so allow skipping these dependencies for projects not using any related components (chart, map or AsciiDoc related).
**_BREAKING CHANGE - MIGRATION GUIDE_**:
The dependency `asciidoctor`, `asciidoctor-highlight.js`, `highlight`, `highchart` and `@highcharts/map-collection` are no longer shipped with `@gravitee/ui-components. 
1. Project using asciidoc …
=> Move some dependencies to peer dependencies

.github/renovate.json
**Issue**
NA
Update Renovate config to group all non-major devDep update in a single PR.
For details see: https://docs.renovatebot.com/configuration-options/#packagerules
=> Update Renovate config to group all non-major devDep update in a single PR

src/index.js, src/molecules/gv-code-hint.js, src/molecules/gv-expression-language.js, wc/gv-code-hint.js
**Issue**
- Related to gravitee-io/issues#4943
- Fix #364
Before this, the "hint" element was a children of `<gv-expression-language>` component which itself was a child of the component's container. (the scrollable element)
The fix is to move "hint" element in the `document.body` to not have the scroll behaviour.
But that poses another problem: the loss of context.
In our case, the CSS.
Using a new component allows you to have an element with your own CSS.
=> fix(gv-expression-language): resolve hint overlay

src/organisms/gv-schema-form-control.js, src/organisms/gv-schema-form.js, stories/organisms/gv-schema-form.stories.js, stories/organisms/gv-schema-form.test.js, stories/resources/schemas/mixed.json
fixes gravitee-io/gravitee-ui-components#350
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/350
Addition of a DSL into the x-schema-form entry of the gv-schema-form component.
This DSL allows to disable a field that matches conditions.
=> feat: add DSL to disable a field that matches some condition

src/policy-studio/gv-policy-studio.js, stories/policy-studio/gv-policy-studio.stories.js, stories/policy-studio/gv-policy-studio.test.js, stories/resources/schemas/am.json
fixes gravitee-io/gravitee-ui-components#349
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/349
Create flow instance based on the flow schema to avoid ugly conditions to adapt the flow content for APIM or AM
=> feat: create flow structure based on the flow schema

src/charts/gv-chart-gauge.js, stories/charts/gv-chart-gauge.stories.js
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/693
Update gauge to allow custom backgroud and tooltip on cockpit a
=> feat(gv-chart-gauge): update gauge chart options

package-lock.json, src/molecules/gv-code.js
Just declare a `clipboard` boolean property
Useful to replace codemirror in APIM console in the log detail view (gravitee-io/issues#5364)
=> fix(gv-code): re-activate clipboard icon

package.json, tasks/generate-dist.js
**Issue**
Closes https://github.com/gravitee-io/gravitee-ui-components/issues/275
Minification was causing issues with Webpack 5 and didn't really offer any benefits for users
working with a bundler.
**How to test**
Locally run: 
```sh
npm run build
cd dist
npm link
npm link @gravitee/ui-components
```
=> Remove source minification when building the package

src/policy-studio/gv-policy-studio.js
=> fix(gv-policy-studio): use correct icon and name for `try it` tab

src/organisms/gv-schema-form-control.js, src/organisms/gv-schema-form.js, stories/organisms/gv-schema-form.test.js, stories/resources/schemas/mixed.json
Some improvements of `gv-schema-form` component.
The goal is to have more possibility for hide some fields.
Related to gravitee-io/issues#5948 and gravitee-io/issues#5972
=> feat(gv-schema-form): add simple hidden field support

src/molecules/gv-row.js
fixes gravitee-io/issues#5761
fixes  #445
=> fix: do not shrink row content if there are a lot of metadata

package-lock.json, src/atoms/gv-select-native.js, src/atoms/gv-select.js, src/index.js, src/mixins/input-element.js, src/organisms/gv-schema-form-control.js, src/styles/input.js, stories/atoms/gv-select-native.stories.js, stories/molecules/gv-table.stories.js, stories/organisms/gv-schema-form.test.js, stories/resources/schemas/mixed.json, wc/gv-select-native.js
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/251
https://github.com/gravitee-io/gravitee-ui-components/issues/329
https://github.com/gravitee-io/issues/issues/6487
Sorry for the duplication...
I kept the `<gv-select>` to not create a breaking change and for the story `TransparentOnDarkBackground` which can't be reimplemented correctly with this new component.
Later, it would be nice to turn the `gv-select` into a `gv-listbox` or something like that, letting users build the list via the `slot`, this would allow better customization and data event binding possibilities.
=> add new gv-select-native component 

src/atoms/gv-select-native.js, src/atoms/gv-select.js, src/organisms/gv-schema-form.js, stories/charts/gv-chart-pie.stories.js, stories/lib/make-story.js, stories/lib/sequence.js, stories/organisms/gv-schema-form.test.js
**Issue**
NA
1. Some fixes after upgrade to Lit 2
- revert unneeded changed introduced in upgrade to Lit 2 
- wait for Lit component to be ready before updating their properties
- replace getter/setter with `willUpdate` function to follow: https://lit.dev/docs/components/properties/#accessors-custom
> In most cases, you do not need to create custom property accessors. To compute values from existing properties, we recommend using the willUpdate callback, which allows you to set values during the update cycle without triggering an additional update. To perform a custom action after the element updates, we recommend using the updated callback. A custom setter can be used in rare cases when it's important to synchronously validate any value the user sets.
2. Improvements …
=> Clean after upgrade to lit2

src/atoms/gv-select-native.js, src/atoms/gv-select.js
In Lit 2 documentation,
**willUpdate()**
`changedProperties`:`Map` with keys that are the names of changed properties and values that are the corresponding **previous values**.
https://lit.dev/docs/components/lifecycle/#reactive-update-cycle
=>  fix: resolve will update implementation 

src/organisms/gv-schema-form.js
**Issue**
https://github.com/gravitee-io/issues/issues/6781
to allow additionalProperties we need to init empty object and not define it to true
See code [here](https://github.com/tdegrunt/jsonschema/blob/6f6512981327c20802852fa32fa3dd4f315f7ce1/lib/attribute.js#L303)
=> fix: init additionalProperties with an empty object to allow them

src/organisms/gv-http-client/gv-http-client.js
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/539
Change `repeat` import from `lit-html` to `lit`
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gbwvuryxsp.chromatic.com)
**🔥  Result**
=> fix(gv-http-client): fix Lit import for repeat directive

src/lib/text-format.js
**Issue**
https://github.com/gravitee-io/issues/issues/6952
Replace href links to include potential parts of the URL that can be set by Angular router or any other routing framework. By default, href will have the following format: href="[SERVER_BASE]/#a_link" i.e. href="https://apim-master-portal.cloud.gravitee.io/#a_link"
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-auiidkcfai.chromatic.com)
=> Override href from asciidoctor ToC

package.json, yarn.lock
**Issue**
NA
Updating semantic-release to v19 has caused some weird behavior in `yarn.lock`
with chalk version range being `*` instead of the version defined in `npm` package.
For details, see: https://github.com/semantic-release/semantic-release/issues/2323
This problem was causing the release to fail with
This reverts commit edd755e2eea565737ab81ca4b6652f76dc29e37e.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-jtvylgvazs.chromatic.com)
=> fix: revert "chore(deps): update dependency semantic-release to v19"

.circleci/config.yml
**Issue**
NA
😱  We are running out of credits for Chromatic so I added back the manual validation before Chromatic job in PR workflow.
This reverts commit bfe5faa3f2bc6d925dbe41e54898cf3e7758bad2.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-kamngrwrfw.chromatic.com)
=> Revert "ci: remove manual approval to run chromatic job"

src/policy-studio/gv-policy-studio/gv-policy-studio.js
**Issue**
We introduced a regression with rework for debug mode. 
We cannot add a policy to a flow.
It's reproductible with Policy Studio / Empty story, just try to drag and drop a policy.
gravitee-io/issues#7159
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-cryvntinxg.chromatic.com)
=> fix(gv-policy-studio): auto submit dirty form if is necessary

src/lib/studio.js, src/policy-studio/gv-policy-studio/gv-policy-studio.test.js, testing/resources/am-definition.json, testing/resources/schemas/am.json
**Issue**
https://github.com/gravitee-io/issues/issues/7193
This PR handles new icons for new AM flows.
as discussed with @gaetanmaisse and @ThibaudAV some work will be done to handle `shape` in the flow schemas
in the future.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-lglghnfmps.chromatic.com)
=> feat: add icons for new AM flows

src/policy-studio/gv-design/gv-design.js, src/policy-studio/gv-policy-studio/gv-policy-studio.js
**Issue**
na
fix this : 
in the debug (without menu) when add a policy then add a description and then we have to validate twice 
in the policy studio (with menu) in all cases when we modify the policy description we have to validate twice
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-qneeeswngk.chromatic.com)
=> fix: not click twice to validate policy schema-form

src/atoms/gv-date-picker/gv-date-picker.js, src/atoms/gv-input/gv-input.js, src/atoms/gv-relative-time/gv-relative-time.js, src/atoms/gv-select-native/gv-select-native.js, src/molecules/gv-confirm/gv-confirm.js, src/molecules/gv-popover/gv-popover.js
**Issue**
https://github.com/gravitee-io/issues/issues/6666
add webpack config to limit languages imported by the dependencies
I looked for other solutions. But they are all more complex
And I think that ui-component should not support all languages but only a set of languages chosen by the product
And that all this work should be done for a specific multilingual topic
=> perf: add webpack config to limit languages imported by the dependencies

src/lib/text-format.js
**Issue**
https://github.com/gravitee-io/issues/issues/6666
load asciidoctor & asciidoctor-highlight.js separately
it allows to load asciidoctor before and to add the retention later
=> feat: load asciidoctor & asciidoctor-highlight.js separately

src/atoms/gv-icon/gv-icon.js
```ts
/**
* Interprets a template literal as an SVG fragment that can efficiently
* render to and update a container.
*
* ```ts
* const rect = svg`<rect width="10" height="10"></rect>`;
*
* const myImage = html`
*   <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
*     ${rect}
*   </svg>`;
* ```
*
* The `svg` *tag function* should only be used for SVG fragments, or elements
* that would be contained **inside** an `<svg>` HTML element. A common error is
* placing an `<svg>` *element* in a template tagged with the `svg` tag
* function. The `<svg>` element is an HTML element and should be used within a
* template tagged with the {@linkcode html} tag function.
*
* In LitElement usage, it's invalid to return an SVG fragment from the
* `render()` method, as the SVG fragment will be …
```
=> fix(gv-icon): use svg lit directive

src/molecules/gv-rating-list/gv-rating-list.js, src/molecules/gv-rating-list/gv-rating-list.stories.js
**Issue**
https://github.com/gravitee-io/issues/issues/6869
Rework event handling in `gv-rating-list` to fix click on `Answer` button.
Also, update the story to use play function and so have a more relevant snapshot
**To test**
Try to click on `Reply` in https://components.gravitee.io/?path=/story/molecules-gv-rating-list--add-answer -> Nothing happens
Play with https://5ffff84833d7150021078521-lpogtxwzsw.chromatic.com/?path=/story/molecules-gv-rating-list--add-answer -> 🎉  (The story itself is clicking on the button + adding some content)
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-lpogtxwzsw.chromatic.com)
=> Rework event handling in gv-rating-list to fix click on `Answer` button

src/policy-studio/gv-design/gv-design.js
**Issue**
https://github.com/gravitee-io/issues/issues/7693
feat: hide closed plans in design studio
Now, when retrieving an api using the endpoint /api/{id},
It returns all plans, including closed ones.
So, we have to hide them in design studio.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ewlnectgjf.chromatic.com)
=> feat: hide closed plans in design studio

src/policy-studio/gv-design/gv-design.js, src/policy-studio/gv-design/gv-design.test.js, src/policy-studio/gv-policy-studio/gv-policy-studio.js, src/policy-studio/gv-policy-studio/gv-policy-studio.test.js, testing/resources/apim-definition-empty-plans.json, testing/resources/apim-definition.json, testing/resources/schemas/apim-configuration.json
**Issue**
gravitee-io/issues#7625
Reword all ``flow-mode`` into ``flow_mode``. The goal is to be consistent everywhere on all supported versions. Today we are juggling between both wordings and it creates bugs. 
In the commit 21e9bc0 I'm updating some test to avoid having UnhandledPromiseRejection. With node 16 those errors make the ``yarn test`` fail but not with node 14. 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-csknuwoozb.chromatic.com)
=> fix: flow mode

src/molecules/gv-cron-editor/gv-cron-editor.js
=> fix: keep event listener for gv-cron-editor when disabled state change

src/organisms/gv-schema-form-group/gv-schema-form-group.js, src/organisms/gv-schema-form-group/gv-schema-form-group.stories.js, src/organisms/gv-schema-form-group/gv-schema-form-group.test.js, src/organisms/gv-schema-form-group/index.ts, wc/gv-schema-form-group.js
**Issue**
n/a 
This component come from gv-shema-form but without submit / cancel feature. The goal of this one is to be used by angular inside reactive form (simply)
Component with medium term goal. The idea is to use it for all schema form needs in Gravitee console during the angularJs migration. Until it is replaced by native angular one
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-hxfpzpqgcp.chromatic.com)
=> feat: add new gv-shema-form-group

.circleci/config.yml
**Issue**
NA
`gravitee-qa` context contains only SONAR_TOKEN which is already available throught the `cicd-orchestrator` context
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-fyjbycvind.chromatic.com)
=> Remove unneeded CircleCI context

src/policy-studio/gv-policy-studio-menu/gv-policy-studio-menu.js, testing/resources/apim-definition.json
**Issue**
https://gravitee.atlassian.net/browse/APIM-983
https://github.com/gravitee-io/issues/issues/8909
Handle plans named with a special character by properly removing all special characters when computing plan id
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-wubdzpsuhx.chromatic.com)
=> fix(gv-policy-studio): handle plans named with a special character

src/charts/gv-chart-line/gv-chart-line.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-878
https://github.com/gravitee-io/issues/issues/5852
Reduce the max number of elements in the tooltip columns to ensure everything is visible when there are a lot of series displayed
_Before_
_After_
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-uqcszjuplb.chromatic.com)
=> fix(gv-chart-line): reduce max number of element in tooltip column

.circleci/config.yml
**Issue**
NA
We are now on a `Standard Plan` with 80 000 snapshots so let's use them
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-msnbaqwynh.chromatic.com)
=> Automatically run Chromatic when branch is pushed

src/atoms/gv-input/gv-input.js, src/organisms/gv-schema-form-control/gv-schema-form-control.js, src/organisms/gv-schema-form/gv-schema-form.stories.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-898
https://github.com/gravitee-io/issues/issues/8590
Handle disabled state on input with x-schema-form condition when loading
**Screenshot**
Before
After
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-nfnmcvuvak.chromatic.com)
=> Handle disabled state on input with x-schema-form condition when loading

jest.setup.js, package.json, src/atoms/gv-select/gv-select.js, src/atoms/gv-select/gv-select.stories.js, yarn.lock
**Issue**
https://gravitee.atlassian.net/browse/APIM-866
https://github.com/gravitee-io/issues/issues/8348
Correctly display and place options list when used in a small container
Delegate option list placement to `popper.js` to ensure correct behaviour.
Before
After
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-mwmvdfcmsr.chromatic.com)
=> fix(gv-select): correctly display and place option list when used in a small container

src/organisms/gv-schema-form-group/gv-schema-form-group.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-1144
Dispatch input event to work with Angular's ngDefaultControl
In some cases like copy and paste or select angular does not detect any change because it is waiting for an "input" event. Yes it's a fix on a hack already in place and commonly used in the portal. For the console this is temporary and soon replaced by native angular components
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ssunaramxn.chromatic.com)
=> fix: dispatch input event to work with Angular's ngDefaultControl

src/molecules/gv-tree/gv-tree.js, src/molecules/gv-tree/gv-tree.stories.js
**Issue**
before : 
after : 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ubswmgsuug.chromatic.com)
=> fix: keep name text aline left when is long string

src/charts/gv-chart-map/gv-chart-map.js, src/charts/gv-chart-map/gv-chart-map.stories.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-909
https://github.com/gravitee-io/issues/issues/8230
Use `hc-key` ref in map to ensure china is properly identified
Quote from https://www.highcharts.com/forum/viewtopic.php?t=33579#p117910:
> 'hc-a2' has CN assigned to 2 regions: 'China' and 'Cyprus No Mans Area'.
> 'hc-a2' in custom/world.js map is not a unique key property. Use 'hc-key' instead.
Before:
After: 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-pwuznzlxcr.chromatic.com)
=> Use `hc-key` ref in map to ensure china is properly identified

src/organisms/gv-schema-form-control/gv-schema-form-control.js, src/organisms/gv-schema-form-group/gv-schema-form-group.stories.js, testing/resources/schemas/policy-cache.json
**Issue**
https://gravitee.atlassian.net/browse/APIM-2085
So that the plugin's json schema is compatible with the 2 json-schema components. I add some capabilities to this one.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-dtvzbejpwg.chromatic.com)
=> feat: use gioConfig.banner.text as description by default

src/molecules/gv-tree/gv-tree.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-3130
Remove nesting of folders in Portal documentation file tree.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-hszqznymwx.chromatic.com)
=> fix: remove nesting of folder arrows

src/lib/studio.js, src/organisms/gv-schema-form/gv-schema-form.test.js, src/policy-studio/gv-design/gv-design.test.js, src/policy-studio/gv-policy-studio/gv-policy-studio.test.js, testing/resources/schemas/apim-flow.json, testing/resources/schemas/fields-dependencies.json, testing/resources/schemas/mixed.json
**Issue**
https://gravitee.atlassian.net/browse/APIM-3569
Use the same kind of algorithm as in the gateway to build the flow name. This way, it will reflect a little bit better what the user can expect.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ghrfjsymyp.chromatic.com)
=> Compute flow name to reflect gateway behaviourr

src/molecules/gv-tree/gv-tree.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-3740
The `gv-tree` menu is to be closed by default + add attribute for tooltip on closed
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-zavgilaeyp.chromatic.com)
=> feat: collapse gv-tree by default

src/lib/item.js, src/molecules/gv-card-full/gv-card-full.js, src/molecules/gv-card-full/gv-card-full.stories.js
see https://gravitee.atlassian.net/browse/APIM-3892
=> feat: render markdown in gv-card-full description

src/organisms/gv-schema-form/gv-schema-form.js, src/organisms/gv-schema-form/gv-schema-form.test.js, src/policy-studio/gv-design/gv-design.js, src/policy-studio/gv-policy-studio/gv-policy-studio.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-5483
In policy studio when we update the schema form the submit button is disabled. After that if we open or close the policy documentation the button become disabled
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-jhjjoqeenj.chromatic.com)
=> fix: keep "touch" and "dirty" states of gv-schema-form when using policy studio policy and documentation 

src/lib/schema-form.js, src/organisms/gv-resources/gv-resources.js, src/organisms/gv-schema-form-control-object/gv-schema-form-control-object.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-6736
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-shmqepndnt.chromatic.com)
=> fix: schema.required is not a mandatory property

src/lib/text-format.js
**Issue**
When upgrading `portal-webui` to Angular 19, a compile error was thrown:
```
[ERROR] No matching export in "node_modules/@gravitee/ui-components/node_modules/dompurify/dist/purify.es.mjs" for import "sanitize"
node_modules/@gravitee/ui-components/src/lib/text-format.js:43:9:
43 │ import { sanitize } from 'dompurify';
╵          ~~~~~~~~
```
To fix the error, the import is handled differently in `text-format.js`.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gorqhmkzvw.chromatic.com)
=> refactor: change how sanitize from DOMPurify is imported

package.json, yarn.lock
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/APIM-8690
Changed the version of json schema
=> fix: json schema version
