src/atoms/gv-button.js, src/atoms/gv-icon.js, src/atoms/gv-nav-link.js, src/atoms/gv-state.js, src/atoms/gv-tag.js, src/icons/gv-icons.js, src/lib/style.js, stories/atoms/gv-button.stories.js, stories/atoms/gv-nav-link.stories.js, stories/atoms/gv-state.stories.js, stories/atoms/gv-tag.stories.js, stories/molecules/gv-nav.stories.js, themes/gravitee-theme.css, wc/gv-state.js, wc/gv-tag.js
Closes gravitee-io/issues#2785
=> feat: add tag & state component

src/atoms/gv-input.js
Closes gravitee-io/issues#2810
=> feat(portal): add name to gv-input tag, allowing field autocompletion

themes/gravitee-theme.css
Closes gravitee-io/issues#2810
=> feat(portal): add a default logo for gravitee theme

src/atoms/gv-card-category.js, stories/atoms/gv-card-category.stories.js, wc/gv-card-category.js
Closes gravitee-io/issues#2851
=> feat(ui-components): add a card component

stories/atoms/gv-card-category.stories.js
=> fix(ui-components): fix gv-card-category documentation in story

assets/css/gravitee-theme.css, src/atoms/gv-card-category.js, stories/atoms/gv-card-category.stories.js, stories/others/colors.stories.js
Closes gravitee-io/issues#2788
=> feat(portal): change gv-card-category to fit new portal design

assets/css/gravitee-theme.css, src/atoms/gv-select.js, src/organisms/gv-user-menu.js, stories/atoms/gv-select.stories.js, wc/gv-select.js
=> feat: Implement the gv-select component

src/atoms/gv-checkbox.js, stories/atoms/gv-checkbox.stories.js, wc/gv-checkbox.js
Closes gravitee-io/issues#2931
=> feat: Create a checkbox component

src/atoms/gv-select.js
Closes gravitee-io/issues#2933
=> fix: Click should not be allowed when gv-select is disabled

.storybook/config.js, src/atoms/gv-checkbox.js, src/atoms/gv-input.js, src/atoms/gv-select.js, src/atoms/gv-text.js
=> feat: Allow a user to contact owner of the platform

src/atoms/gv-input.js, stories/atoms/gv-input.stories.js, stories/organisms/gv-menu.stories.js
Closes gravitee-io/issues#2793
=> feat(portal): throw a custom submit event when enterKey is pressed

src/atoms/gv-input.js, src/atoms/gv-select.js, src/organisms/gv-pagination.js, src/styles/input.js, stories/atoms/gv-input.stories.js, stories/atoms/gv-select.stories.js, stories/organisms/gv-pagination.stories.js, wc/gv-pagination.js
=> feat: add pagination component

src/atoms/gv-message.js, stories/atoms/gv-message.stories.js
=> refactor: Remove borders of gv-message

src/atoms/gv-button.js, src/atoms/gv-input.js, src/atoms/gv-message.js, src/atoms/gv-nav-link.js, src/styles/input.js, stories/atoms/gv-button.stories.js, stories/atoms/gv-input.stories.js, stories/atoms/gv-message.stories.js
Closes gravitee-io/issues#2935
=> feat: Display a global loader when calling server

.storybook/preview-head.html, assets/css/gravitee-theme.css, src/atoms/gv-button.js, src/atoms/gv-card-category.js, src/atoms/gv-icon.js, src/atoms/gv-image.js, src/atoms/gv-input.js, src/atoms/gv-select.js, src/atoms/gv-tag.js, src/icons/gv-icons.js, src/mixins/api-element.js, src/molecules/gv-card-api-full.js, src/molecules/gv-card-api.js, src/molecules/gv-option.js, src/molecules/gv-promote-api.js, src/molecules/gv-row-api.js, src/organisms/gv-pagination.js, stories/atoms/gv-button.stories.js, stories/atoms/gv-card-category.stories.js, stories/atoms/gv-input.stories.js, stories/molecules/gv-card-api.stories.js, stories/molecules/gv-option.stories.js, stories/molecules/gv-promote-api.stories.js, stories/molecules/gv-row-api.stories.js, stories/organisms/gv-pagination.stories.js, stories/organisms/gv-user-menu.stories.js, wc/gv-option.js, wc/gv-row-api.js
=> feat: improve components for display an API 

.storybook/config.js, assets/i18n/en.json, assets/i18n/fr.json, package-lock.json, package.json, src/lib/i18n.js, src/organisms/gv-pagination.js, stories/lib/i18n-knob.js, tasks/check-i18n.js
Closes gravitee-io/issues#2940
=> feat: add i18n system

src/organisms/gv-pagination.js
Closes gravitee-io/issues#2965
=> chore(portal): pagination data are now numbers

assets/css/gravitee-theme.css
Closes gravitee-io/issues#2969
=> feat: Add a footer

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-select.js, src/lib/i18n.js, src/mixins/api-element.js, src/molecules/gv-card-api-full.js, src/molecules/gv-card-api.js, src/molecules/gv-promote-api.js, src/molecules/gv-row-api.js
Closes gravitee-io/issues#2955
=> feat: Handle empty states

src/atoms/gv-input.js, src/atoms/gv-text.js, stories/atoms/gv-input.stories.js, stories/atoms/gv-text.stories.js
Closes gravitee-io/issues#2972
=> feat: Autofocus on input / textarea

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-metric.js, src/mixins/api-element.js, src/molecules/gv-card-api-full.js, src/molecules/gv-metrics.js, src/molecules/gv-promote-api.js, src/molecules/gv-rating.js, stories/atoms/gv-metric.stories.js, stories/molecules/gv-card-api-full.stories.js, stories/molecules/gv-metrics.stories.js, stories/molecules/gv-promote-api.stories.js, wc/gv-metric.js, wc/gv-metrics.js
Closes gravitee-io/issues#2960
=> feat(portal): change the way metrics are loaded

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-metric.js, src/atoms/gv-nav-link.js, src/mixins/api-element.js, src/molecules/gv-header-api.js, src/molecules/gv-metrics.js, src/molecules/gv-promote-api.js, src/organisms/gv-menu.js, stories/molecules/gv-card-api-full.stories.js, stories/molecules/gv-header-api.stories.js, stories/molecules/gv-promote-api.stories.js, stories/organisms/gv-menu.stories.js, wc/gv-header-api.js
=> feat: add api header component

assets/css/gravitee-theme.css, src/molecules/gv-tree.js, stories/molecules/gv-tree.stories.js, wc/gv-tree.js
Closes gravitee-io/issues#2796
=> feat(portal): create a tree-view component

package-lock.json, package.json, src/atoms/gv-nav-link.js, src/lib/utils.js, src/mixins/with-resize-observer.js, src/molecules/gv-header-api.js, src/molecules/gv-nav.js, src/organisms/gv-menu.js, stories/molecules/gv-header-api.stories.js, stories/organisms/gv-menu.stories.js
=> feat(gv-menu): improve UX

src/lib/utils.js
=> fix(gv-menu): compare size of active routes before updating

src/molecules/gv-nav.js
=> fix(gv-nav): add lock until the click ends

assets/i18n/en.json, assets/i18n/fr.json, src/molecules/gv-header-api.js
Closes gravitee-io/issues#3011
=> refactor: Extract contact as a component

src/atoms/gv-button.js, src/atoms/gv-nav-link.js, src/organisms/gv-user-menu.js
=> feat: design homepage

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-tag.js, src/mixins/api-element.js, src/molecules/gv-info-api.js, src/molecules/gv-list.js, src/molecules/gv-rating.js, stories/molecules/gv-card-api-full.stories.js, stories/molecules/gv-info-api.stories.js, stories/molecules/gv-list.stories.js, stories/molecules/gv-row-api.stories.js, wc/gv-info-api.js, wc/gv-list.js
Closes gravitee-io/issues#2789
=> feat(portal): allow a user to display an API

src/organisms/gv-user-menu.js
Closes gravitee-io/issues#3037
=> fix: Fix user menu

src/molecules/gv-info-api.js, src/molecules/gv-rating.js
=> fix(portal): fix ratings rendering when used in gv-info-api

src/atoms/gv-link.js, src/molecules/gv-header-api.js, src/molecules/gv-nav.js, src/molecules/gv-tree.js, src/organisms/gv-menu.js, src/organisms/gv-user-menu.js, stories/atoms/gv-link.stories.js, stories/molecules/gv-header-api.stories.js, stories/molecules/gv-nav.stories.js, stories/molecules/gv-tree.stories.js, stories/organisms/gv-menu.stories.js, stories/organisms/gv-user-menu.stories.js, wc/gv-link.js, wc/gv-nav-link.js
Closes gravitee-io/issues#2954
=> refactor: rename gv-nav-link to gv-link

src/lib/utils.js, src/molecules/gv-nav.js, stories/molecules/gv-nav.stories.js
=> fix(nav): resolve navigation state

src/atoms/gv-link.js, src/atoms/gv-message.js, src/molecules/gv-info.js, src/molecules/gv-nav.js, stories/molecules/gv-info.stories.js
Closes gravitee-io/issues#3048
=> feat(portal): gv-link can now refer to an external link

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-select.js, src/molecules/gv-list.js, src/organisms/gv-menu.js, stories/organisms/gv-menu.stories.js
=> feat: improve components for subscription

src/molecules/gv-promote.js, stories/molecules/gv-promote.stories.js
Closes gravitee-io/issues#3116
=> fix: Display labels on API cards

src/organisms/gv-user-menu.js
Closes gravitee-io/issues#3036
=> chore: remove useless "tachyons" library

src/atoms/gv-input.js, stories/atoms/gv-input.stories.js
=> feat(input): add autocomplete attribute

src/atoms/gv-checkbox.js, stories/atoms/gv-checkbox.stories.js
Closes gravitee-io/issues#3179
=> feat: Improve gv-checkbox's design

src/molecules/gv-user-avatar.js
Closes gravitee-io/issues#3192
=> fix: Avatar cannot be changed the first time

src/atoms/gv-button.js, src/atoms/gv-checkbox.js, src/atoms/gv-image.js, src/atoms/gv-input.js, src/atoms/gv-text.js, src/molecules/gv-card-full.js, src/molecules/gv-info.js, src/molecules/gv-list.js, src/molecules/gv-table.js, stories/atoms/gv-input.stories.js, stories/atoms/gv-text.stories.js
Closes gravitee-io/issues#2799
=> feat: Allow a user to consult/edit global settings of an application

src/molecules/gv-rating-list.js, stories/molecules/gv-rating-list.stories.js
=> refactor(gv-rating-list): change permissions system

assets/i18n/en.json, assets/i18n/fr.json, src/molecules/gv-info.js, src/molecules/gv-plans.js, stories/molecules/gv-plans.stories.js
=> fix(gv-plans): resolve single item display

.storybook/preview.js, assets/i18n/en.json, assets/i18n/fr.json, package-lock.json, package.json, src/atoms/gv-button.js, src/atoms/gv-select.js, src/charts/gv-chart-line.js, src/charts/gv-chart-map.js, src/charts/gv-chart-pie.js, src/index.js, src/mixins/chart-element.js, src/molecules/gv-category.js, src/molecules/gv-stats.js, src/molecules/gv-table.js, src/organisms/gv-pagination.js, src/styles/skeleton.js, stories/atoms/gv-button.stories.js, stories/charts/gv-chart-line.stories.js, stories/charts/gv-chart-map.stories.js, stories/charts/gv-chart-pie.stories.js, stories/molecules/gv-stats.stories.js, stories/molecules/gv-table.stories.js, wc/gv-chart-line.js, wc/gv-chart-map.js, wc/gv-chart-pie.js, wc/gv-stats.js
Closes gravitee-io/issues#2804
=> feat: Allow a user to consult analytics of an application

src/organisms/gv-user-menu.js, stories/organisms/gv-user-menu.stories.js
Closes gravitee-io/issues#3109
=> feat(portal) : add management link in portal usermenu

src/atoms/gv-switch.js
Closes gravitee-io/issues#3115
=> feat: Allow a user to subscribe to notifications on an application

src/atoms/gv-autocomplete.js, src/atoms/gv-file-upload.js, src/atoms/gv-input.js, src/atoms/gv-select.js, src/atoms/gv-switch.js, src/atoms/gv-tag.js, src/atoms/gv-text.js, src/mixins/input-element.js, src/molecules/gv-plans.js, src/molecules/gv-table.js, src/organisms/gv-menu.js, src/styles/input.js, src/theme/definition.json, stories/atoms/gv-autocomplete.stories.js, stories/atoms/gv-input.stories.js, stories/molecules/gv-plans.stories.js, stories/molecules/gv-table.stories.js, stories/organisms/gv-menu.stories.js
=> feat: Allow a user to create an application

src/atoms/gv-message.js, src/atoms/gv-select.js, src/molecules/gv-info.js, src/molecules/gv-table.js, src/theme/definition.json, stories/atoms/gv-select.stories.js
Closes gravitee-io/issues#3114
=> feat: Allow a user to consult subscriptions of an application

src/atoms/gv-select.js, src/charts/gv-chart-line.js, src/molecules/gv-table.js, src/theme/definition.json
Closes gravitee-io/issues#2805
=> feat: Allow a user to consult logs of an application

src/charts/gv-chart-line.js, src/charts/gv-chart-map.js, src/charts/gv-chart-pie.js, src/mixins/chart-element.js
=> chore: use webpack dynamic import in charts

src/mixins/item-resource.js, src/molecules/gv-category.js, src/organisms/gv-header.js
Closes gravitee-io/issues#3178
=> feat(portal): display Views picture

src/molecules/gv-row.js, src/organisms/gv-menu.js
=> fix: improve search input results display

src/mixins/item-resource.js, src/molecules/gv-promote.js
=> fix: resolve gv-rating integration in gv-promote

src/mixins/item-resource.js, src/molecules/gv-list.js, src/molecules/gv-promote.js
Closes gravitee-io/issues#3436
=> feat(portal): use api version to generate default picture

src/molecules/gv-tree.js, src/theme/definition.json
=> feat: change gv-tree default colors

src/molecules/gv-identity-picture.js, src/molecules/gv-table.js, src/organisms/gv-pagination.js, src/organisms/gv-user-menu.js, src/theme/definition.json, stories/molecules/gv-identity-picture.stories.js
=> feat: Add browsers notifications

src/molecules/gv-identity-picture.js
=> fix: Avoid multiple calls on API/App page

src/molecules/gv-category.js, src/molecules/gv-identity-picture.js, src/theme/definition.json, stories/molecules/gv-category-list.stories.js, stories/molecules/gv-category.stories.js, stories/molecules/gv-identity-picture.stories.js
fix gravitee-io/issues#3467
fix gravitee-io/issues#3453
=> fix: resolve category image position

package.json, pom.xml, src/atoms/gv-date-picker-calendar.js, src/atoms/gv-date-picker-cell.js, src/index.js, tasks/generate-dist.js, tasks/size.js
=> chore: improve dist generation

src/atoms/gv-message.js, stories/atoms/gv-message.stories.js
Closes gravitee-io/issues#2956
=> feat(portal): make gv-message closable & add a closeEvent to gvPopover

src/mixins/item-resource.js, src/molecules/gv-card-list.js, src/molecules/gv-card.js, src/molecules/gv-identity-picture.js, src/organisms/gv-header.js, src/organisms/gv-menu.js, src/theme/definition.json, stories/molecules/gv-category-list.stories.js
=> fix: Sometimes, screen is loading indefinitely

src/organisms/gv-menu.js, stories/organisms/gv-menu.stories.js
=> fix(portal): set right slot width to 100%

src/atoms/gv-input.js, src/atoms/gv-select.js, src/mixins/input-element.js, src/styles/input.js, stories/atoms/gv-input.stories.js, stories/atoms/gv-message.stories.js
=> fix: allow user to save credentials

src/molecules/gv-table.js
=> fix: JS error when refreshing the subscription's page

src/atoms/gv-relative-time.js, src/molecules/gv-rating-list.js
=> fix: Last updated at for API is not well formed

.storybook/preview-head.html, stories/documentation/gv-theme.stories.js
=> fix(ui-components): display labels on colors in theme

src/molecules/gv-identity-picture.js, src/organisms/gv-user-menu.js, stories/molecules/gv-identity-picture.stories.js, stories/organisms/gv-user-menu.stories.js
=> feat: add rounded attribute to gv-identity-picture

src/organisms/gv-menu.js
=> fix(gv-menu): resolve truncated text on right slots

assets/i18n/en.json, assets/i18n/fr.json
=> fix(portal): change gv-metrics example labels

src/atoms/gv-date-picker.js
=> fix(gv-date-picker): update input when value change

assets/i18n/en.json, assets/i18n/fr.json, package-lock.json, package.json, src/lib/i18n.js, src/molecules/gv-metrics.js, stories/molecules/gv-metrics.stories.js
=> fix(portal): webcomponent translations can have parameters

README.adoc, package.json, pom.xml
Closes gravitee-io/issues#3624
=> feat(chore): replace 'start' by 'serve'

src/atoms/gv-button.js, src/atoms/gv-relative-time.js, src/molecules/gv-info.js, src/molecules/gv-popover.js, src/molecules/gv-rating-list.js
=> fix: manage my api-keys

src/atoms/gv-autocomplete.js, src/atoms/gv-input.js, stories/atoms/gv-autocomplete.stories.js
=> fix: remove auto submit on autocomplete

src/mixins/item-resource.js, src/molecules/gv-identity-picture.js, src/molecules/gv-rating-list.js, src/molecules/gv-rating.js
=> fix(gv-card): resolve size of identidy-picture

src/molecules/gv-list.js, stories/molecules/gv-list.stories.js
=> fix(portal): gv-list are now clickable to navigate to apis and apps

src/atoms/gv-file-upload.js, src/atoms/gv-input.js, src/atoms/gv-message.js, src/atoms/gv-select.js, src/atoms/gv-text.js, src/mixins/input-element.js, src/molecules/gv-confirm.js, src/molecules/gv-identity-picture.js, src/molecules/gv-popover.js, src/molecules/gv-rating-list.js, src/molecules/gv-table.js, stories/atoms/gv-file-upload.stories.js, stories/atoms/gv-input.stories.js
fix gravitee-io/issues#3463
fix gravitee-io/issues#3544
=> feat: use same file-upload component

src/atoms/gv-metric.js, src/mixins/item-resource.js, src/molecules/gv-card-full.js, src/molecules/gv-info.js, src/molecules/gv-metrics.js, src/molecules/gv-promote.js, src/molecules/gv-rating.js, src/styles/skeleton.js, stories/molecules/gv-card-full.stories.js, stories/molecules/gv-metrics.stories.js, stories/molecules/gv-promote.stories.js
=> feat: improve display of metrics

src/atoms/gv-date-picker.js, src/atoms/gv-input.js, src/charts/gv-chart-line.js, src/mixins/chart-element.js, src/molecules/gv-option.js, stories/molecules/gv-option.stories.js
=> fix: Date range seems not handling well time zone

src/molecules/gv-info.js
=> fix: Display to consumer entrypoints of the API

src/molecules/gv-category.js
=> fix: display total apis of a category in card

src/molecules/gv-popover.js
=> fix: resolve popover above position

src/mixins/chart-element.js, src/molecules/gv-stats.js, stories/molecules/gv-stats.stories.js
=> fix: Empty state not working on widget stats

assets/i18n/en.json, assets/i18n/fr.json, src/atoms/gv-button.js, src/mixins/item-resource.js, src/molecules/gv-code.js, src/molecules/gv-confirm.js, src/molecules/gv-info.js, src/molecules/gv-popover.js, src/molecules/gv-promote.js, src/molecules/gv-table.js, src/theme/definition.json, stories/atoms/gv-button.stories.js, stories/molecules/gv-code.stories.js, stories/molecules/gv-promote.stories.js, stories/molecules/gv-table.stories.js
=> fix(ui-components): fix an undefined error

src/molecules/gv-confirm.js, src/molecules/gv-tree.js
=> feat(gv-tree): improve display with scrollbar

src/molecules/gv-stats.js, src/molecules/gv-table.js, src/styles/empty.js
=> feat: User dashboard

src/atoms/gv-input.js, src/atoms/gv-select.js, src/atoms/gv-text.js, src/lib/item.js, src/mixins/input-element.js, src/mixins/item-resource.js, src/molecules/gv-card-full.js, src/molecules/gv-card.js, src/molecules/gv-category.js, src/molecules/gv-confirm.js, src/molecules/gv-info.js, src/molecules/gv-list.js, src/molecules/gv-promote.js, src/molecules/gv-row.js, src/organisms/gv-header.js, stories/atoms/gv-input.stories.js, stories/atoms/gv-select.stories.js, stories/atoms/gv-text.stories.js, stories/molecules/gv-category.stories.js
=> feat: improve readonly mode on inputs

src/organisms/gv-user-menu.js
=> fix: Avoid to select user menu text

src/atoms/gv-button.js, stories/atoms/gv-button.stories.js
=> fix: Improve loader on gv-button

src/lib/item.js
=> fix(portal): generate a view default image with the right title

src/charts/gv-chart-pie.js
=> fix: Pie charte is displaying NaN when no value

src/molecules/gv-stats.js
=> fix(ui-components): fix variable name

src/molecules/gv-promote.js, stories/molecules/gv-promote.stories.js
=> fix(ui-components): truncate description if too long

src/molecules/gv-promote.js, stories/molecules/gv-promote.stories.js
=> fix: We should justify text on promote API

src/atoms/gv-button.js, src/atoms/gv-input.js, src/molecules/gv-list.js, src/molecules/gv-option.js, src/molecules/gv-plans.js, src/styles/empty.js, src/theme/definition.json, stories/atoms/gv-button.stories.js
fix gravitee-io/issues#3543
fix gravitee-io/issues#3750
=> fix: improve components for application's grant flow

src/lib/item.js
=> fix(ui): Generate the application picture using owner name

src/atoms/gv-file-upload.js
=> fix: resolve multiple upload of same file in chrome

src/atoms/gv-button.js, src/atoms/gv-date-picker-calendar.js, src/atoms/gv-date-picker.js, src/molecules/gv-confirm.js, src/organisms/gv-pagination.js, stories/atoms/gv-button.stories.js
=> feat: improve date picker selection

src/molecules/gv-nav.js
=> feat(gv-nav): add dynamic compact mode

src/molecules/gv-stepper.js, src/theme/definition.json, stories/molecules/gv-stepper.stories.js
=> feat(gv-stepper): add invalid state

src/atoms/gv-button.js, src/molecules/gv-table.js
fix gravitee-io/issues#3784
fix  gravitee-io/issues#3659
=> fix(gv-table): resolve columns alignment

src/molecules/gv-table.js
=> fix(gv-table): resolve resolve selection with specific rowheight

src/atoms/gv-select.js
=> fix(gv-select): reduce triangle

src/atoms/gv-message.js, stories/atoms/gv-message.stories.js
=> feat(gv-message): add default background transparent mode

src/mixins/item-resource.js, src/molecules/gv-card-full.js, src/molecules/gv-metrics.js
=> feat(gv-metrics): add clickable option

src/atoms/gv-select.js, src/molecules/gv-table.js, src/styles/input.js, stories/molecules/gv-table.stories.js
=> fix: resolve gv-table selection

src/molecules/gv-tree.js, src/theme/definition.json
=> fix(ui-components): improve gv-tree

src/molecules/gv-rating-list.js
=> fix(gv-rating-list): mark answer as require

src/molecules/gv-option.js, src/molecules/gv-tree.js, src/theme/definition.json
=> refactor: clean var css documentation & theme

src/atoms/gv-button.js
=> fix(ui-components): change style for link with href

src/molecules/gv-metrics.js, stories/molecules/gv-metrics.stories.js
=> feat(gv-metrics): improve with column mode

src/atoms/gv-tag.js, src/lib/item.js, src/mixins/item-resource.js, src/molecules/gv-card-full.js, src/molecules/gv-promote.js, src/molecules/gv-table.js
Closes gravitee-io/issues#3842
=> feat(portal): enable tags on gv-promote & gv-card-full to be clicked

src/organisms/gv-header.js
=> fix: The subscribe button should not disappear on scroll

src/lib/item.js, src/mixins/item-resource.js, src/molecules/gv-card-full.js, src/molecules/gv-category.js, src/organisms/gv-header.js, stories/organisms/gv-header.stories.js
=> feat: Allows to define a background on the APIs/Apps/Categories headers

src/atoms/gv-checkbox.js
=> fix(gv-checkbox): apply same behavior as native input[type=checkbox]

src/molecules/gv-table.js
=> fix(gv-table): resolve gv-confirm position

CONTRIBUTING.adoc, Jenkinsfile, package-lock.json, package.json, pom.xml, src/atoms/gv-date-picker.js, src/atoms/gv-input.js, src/atoms/gv-select.js, src/molecules/gv-confirm.js, src/molecules/gv-table.js, src/styles/input.js
=> fix(portal): allow to manage Application's metadata from portal

.storybook/main.js, .storybook/preview.js, package-lock.json
=> chore: fix hot reload

src/atoms/gv-input.js
Closes gravitee-io/issues#4341
=> fix: gv-input spinner animation

README.adoc, src/molecules/gv-tree.js, stories/molecules/gv-tree.test.js
=> fix(gv-tree): fix expand of folders in production mode

src/policy-studio/gv-policy-studio.js
=> fix(policy-studio): resolve policy edition of flow plan

src/molecules/gv-table.js
=> feat: support tickets history

src/molecules/gv-row.js, stories/molecules/gv-row.stories.js
=> feat(gv-row): add option small to hide labels

src/atoms/gv-date-picker.js, src/atoms/gv-input.js
=> fix(gv-date-picker): resolve clear icon colors

src/molecules/gv-code.js, stories/molecules/gv-code.stories.js
…exist
fix: gravitee-io/issues#4665
=> fix(gv-code): display codemirror even with a mode that not exist

src/lib/studio.js, src/lib/utils.js, src/molecules/gv-code.js, src/organisms/gv-resources.js, src/policy-studio/gv-policy-studio-menu.js, stories/molecules/gv-code.test.js, stories/organisms/gv-schema-form.stories.js, stories/resources/schemas/groovy.json
=> fix(gv-code): resolve dispatch of change event

src/organisms/gv-schema-form.js, src/policy-studio/gv-policy-studio.js, stories/policy-studio/gv-policy-studio.stories.js, stories/resources/apim-definition.json, stories/resources/schemas/apim-configuration.json
Fixes https://github.com/gravitee-io/issues/issues/4589
=> feat: allow to migrate from policy studio v1 to v2

package-lock.json, package.json, src/molecules/gv-code.js, src/molecules/gv-expression-language.js, src/organisms/gv-schema-form-control.js, src/policy-studio/gv-policy-studio.js, src/styles/input.js, stories/atoms/gv-autocomplete.stories.js, stories/lib/make-story.js, stories/molecules/gv-code.stories.js, stories/molecules/gv-expression-language.stories.js, stories/molecules/gv-expression-language.test.js, stories/organisms/gv-schema-form.stories.js, stories/organisms/gv-schema-form.test.js, stories/resources/el-grammar.json, stories/resources/schemas/mixed.json, wc/gv-expression-language.js
=> feat: add gv-expression-language component

src/atoms/gv-button.js
=> fix(gv-button): show loading on button without icon

src/organisms/gv-schema-form-control.js
=> fix(ui-component): manage password type for schema-form

src/charts/gv-chart-line.js, src/charts/gv-chart-pie.js
Fixes https://github.com/gravitee-io/issues/issues/4747
=> feat: console dashboard page

src/organisms/gv-newsletter-subscription.js
=> fix: newsletter improvment - css issue

src/molecules/gv-code.js
=> fix(gv-code): not load a mode if not defined

src/policy-studio/gv-policy-studio-menu.js, src/policy-studio/gv-policy-studio.js, stories/policy-studio/gv-policy-studio.stories.js, stories/resources/apim-definition-empty-plans.json, stories/resources/apim-definition.json
* fix apidefinition file in policy-studio stories
* remove hasPlans
* add readonly-plans option
Closes gravitee-io/issues#4770
=> feat(gv-policy-studio): add readonly-plans option

src/atoms/gv-spinner.js
=> fix(gv-spinner): add default image

src/charts/gv-chart-line.js
=> feat: display deployments markups on api analytics

assets/i18n/en.json, assets/i18n/fr.json, package-lock.json, package.json, src/atoms/gv-checkbox.js, src/atoms/gv-date-picker-calendar.js, src/atoms/gv-date-picker-cell.js, src/atoms/gv-date-picker.js, src/atoms/gv-input.js, src/atoms/gv-select.js, src/index.js, src/lib/cron-expression.js, src/mixins/input-element.js, src/molecules/gv-cron-editor.js, src/molecules/gv-option.js, src/organisms/gv-properties.js, src/organisms/gv-schema-form-control.js, src/organisms/gv-tabs.js, src/styles/input.js, stories/atoms/gv-autocomplete.test.js, stories/atoms/gv-date-picker.stories.js, stories/atoms/gv-date-picker.test.js, stories/atoms/gv-input.stories.js, stories/lib/cron-expression.test.js, stories/molecules/gv-cron-editor.stories.js, stories/molecules/gv-cron-editor.test.js, stories/organisms/gv-schema-form.test.js, stories/organisms/gv-tabs.stories.js, stories/resources/schemas/mixed.json, wc/gv-cron-editor.js
=>  feat: add gv-cron-editor component

src/atoms/gv-select.js, src/organisms/gv-user-menu.js, src/organisms/gv-vertical-menu.js, src/theme/definition.json, stories/atoms/gv-select.stories.js
Necessary updates for Cockpit UI improvements
=> Feat/cockpit UI polish

.storybook/main.js, .storybook/preview.js, src/atoms/gv-checkbox.js, src/atoms/gv-date-picker-calendar.js, src/atoms/gv-date-picker.js, src/atoms/gv-select.js, src/molecules/gv-option.js, src/organisms/gv-user-menu.js, src/theme/definition.json
=> chore: add prettier

src/atoms/gv-switch.js, src/molecules/gv-code.js, src/molecules/gv-expression-language.js, src/molecules/gv-option.js, src/theme/definition.json
=> [management] Advanced API logging configuration

.circleci/config.yml, package.json
=> CI: Rework CircleCI workflow to use simple Node Docker images

src/molecules/gv-code.js
=> fix(gv-code): resolve display when field has only one row

src/molecules/gv-code.js, stories/molecules/gv-code.stories.js, stories/molecules/gv-expression-language.stories.js, stories/resources/apim-definition.json, stories/resources/apim-policies.json
=> fix(gv-code): resolve display when field has only one row & long content

src/molecules/gv-table.js, src/organisms/gv-properties.js, src/organisms/gv-resources.js, src/theme/definition.json
* default to auto
* set to none for the policy studio
=> fix(gv-table): add a var CSS for overflow

.circleci/config.yml, CHANGELOG.md, package-lock.json, package.json
**Issue**
Part of https://github.com/gravitee-io/gravitee-ui-components/issues/273
The goal of this PR is to introduce CommitLint and use it to ensure the commits messages will be successfully parsed during the release (that will be based on semantic release). It is set up to check the commit both:
- in the CI as part of the `lint-test` job
- in a `commit-msg` hook locally to reject invalid commits directly
=> Add CommitLint with conventional commit config

.circleci/config.yml, CHANGELOG.md, package.json, release.config.js
Various fixes after the 1st automatic release:
- Simplify message commit of the release and temporary disable some rules 
- Export the SecretHub variables with another way to avoid issues with the SecretHub CLI
=> Fix release

src/index.js, src/molecules/gv-modal.js, stories/molecules/gv-modal.stories.js, wc/gv-modal.js
This PR adds a new component: `gv-modal`
=> Add gv modal

src/atoms/gv-select.js, stories/molecules/gv-table.stories.js
=> fix(gv-select): let select go out of parent item

assets/css/codemirror/all.css, package-lock.json, src/atoms/gv-select.js, src/molecules/gv-modal.js, src/theme/definition.json, stories/atoms/gv-date-picker.stories.js, stories/atoms/gv-select.stories.js, stories/molecules/gv-modal.stories.js
Fixes https://github.com/gravitee-io/gravitee-ui-components/issues/284
=> fix: gv-select default background should be white

src/lib/utils.js, stories/lib/utils.test.js
=> fix: let compare null objects

src/atoms/gv-state.js, src/theme/definition.json, stories/atoms/gv-state.stories.js
Handles the following new states:
- error
- status
- warn
=> feat(gv-state): handle new state

src/organisms/gv-menu.js, stories/organisms/gv-menu.stories.js
=> fix(gv-menu): resolve sticky mode

src/atoms/gv-button.js
=> fix(gv-button): rendering problem with skeleton mode

src/molecules/gv-promote.js
=> fix(gv-promote): resolve blink when loading new data

src/molecules/gv-code.js
=> fix(gv-code): remove listeners when disconnect callback

src/organisms/gv-schema-form-control.js, src/organisms/gv-schema-form.js, src/policy-studio/gv-policy-studio.js, stories/organisms/gv-schema-form.stories.js
fix gravitee-io/issues#5351
fix gravitee-io/issues#5336
=> fix(gv-schema-form): fix rerender with validation in policy studio

.github/workflows/codeql-analysis.yml, stories/molecules/gv-stepper.stories.js
**Issue**
NA
- Setup GitHub CodeQL Analysis: https://codeql.github.com/docs/codeql-overview/about-codeql
- Disable Chromatic for `gv-stepper` flaky story
=> chore: init GitHub CodeQL Analysis

src/organisms/gv-schema-form-control.js, src/organisms/gv-schema-form.js, src/policy-studio/gv-flow.js, src/policy-studio/gv-policy-studio-menu.js, src/policy-studio/gv-policy-studio.js, stories/policy-studio/gv-policy-studio.test.js
fix gravitee-io/issues#4460
**Issue**
=> feat(management): platform policies

src/policy-studio/gv-flow.js
Fixes https://github.com/gravitee-io/issues/issues/4460
=> fix(management): platform policies rollback error throwing when no policy

.github/renovate.json
**Issue**
NA
Enable `dependencyDashboard` feature of Renovate.
=> Enable `dependencyDashboard` feature of Renovate

src/mixins/input-element.js, src/molecules/gv-code.js, src/molecules/gv-expression-language.js, stories/policy-studio/gv-policy-studio.stories.js, stories/resources/am-definition.json
**Issue**
fix gravitee-io/issues#5719
Minor fixes and enhancements to use `gv-expression-language` in AM
=> Feat add el in am

src/molecules/gv-table.js, src/organisms/gv-resources.js, src/organisms/gv-schema-form-control.js, src/organisms/gv-schema-form.js, stories/organisms/gv-schema-form.test.js, stories/resources/schemas/mixed.json
Some fix & improvements for gravitee-io/issues#5712
Based on https://json-schema.org/specification.html
=> Resources redis

package.json
**Issue**
NA
Format files with Prettier in pre-commit hook
=> Format files with Prettier in pre-commit hook

package-lock.json, package.json, src/lib/text-format.js, src/molecules/gv-code.js, src/organisms/gv-documentation.js, src/policy-studio/gv-policy-studio.js, stories/molecules/gv-code.stories.js, stories/organisms/gv-documentation.stories.js
**Issue**
https://github.com/gravitee-io/issues/issues/4717
Update `gv-documentation` and `gv-code` to be able to edit and display AsciiDoc documentation
=> feat: update gv-documentation to handle asciidoc

src/policy-studio/gv-policy-studio.js, stories/policy-studio/gv-policy-studio.test.js
Fixes #388
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/388
=> fix(gv-policy-studio): allow to reset condition

src/molecules/gv-code.js, stories/molecules/gv-code.stories.js, stories/molecules/gv-code.test.js
* Manage application/json mode in codemirror
* Send a custom event when value is copied in the clipboard
=> Improvement of gv-code

.husky/commit-msg, .husky/pre-commit, package-lock.json, package.json
**Issue**
NA
- Upgrade Husky from v4 to v7,  for details, see: https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
- Automatically sort `package.json` with `sort-package-json` dep in pre-commit hook
=> Upgrade Husky

.storybook/main.js, stories/atoms/gv-icon.stories.js
**Issue**
NA
Currently, the story isn't working when SB is deployed in "production".
Rewriting the story using bare CSF 3 format could fix the issue.
For details, see https://storybook.js.org/blog/component-story-format-3-0.
=> Rework `gv-icon` story to use Component Story Format V3

.circleci/config.yml, dangerfile.ts, package-lock.json, package.json
**Issue**
NA
Setup [Danger JS](https://github.com/danger/danger-js) and create a simple Dangerfile to comment a PR if the `definition.json` file is updated.
Example:
=> CI: Add Danger JS and check definition.json file modification

src/lib/http-client-schema-form.js, src/organisms/gv-http-client.js
https://github.com/gravitee-io/issues/issues/6016
=> fix(gv-http-client): remove default header value

COMPONENTS_USAGES.md, package-lock.json, package.json, tasks/list-component-dependencies.mjs
**Issue**
https://github.com/gravitee-io/issues/issues/6015
The recap markdown file lists usages of the components across apps of the Gravitee.io ecosystem.
The script lists all the dependencies between components.
=> Create recap file and script to find component usages

src/molecules/gv-table.js
**Issue**
https://github.com/gravitee-io/gravitee-ui-components/issues/453
In a gv-table, the value of a cell is added as the title of the div.
In my context, the content of my cell is too long, so I need to truncate it. But i want the user to have the full information.
=> feat(gv-table): Add cell value as title of a cell

src/policy-studio/gv-policy-studio.js
=> fix(gv-policy-studio): always submit valid forms

src/mixins/update-after-browser.js, src/organisms/gv-schema-form-array.js, src/organisms/gv-schema-form-control-object.js, src/organisms/gv-schema-form-control.js, stories/organisms/gv-schema-form.test.js
=> fix(gv-schema-form): wait browser refresh before update

src/molecules/gv-card-full.js, src/molecules/gv-promote.js, stories/molecules/gv-card-full.stories.js, stories/molecules/gv-promote.stories.js
**Issue**
https://github.com/gravitee-io/issues/issues/6485
For promote : 
For card-full
=> 6485 display owner

src/atoms/gv-button.js
**Issue**
na
try to fix this errors : 
=> fix: remove unnecessary perform update

src/molecules/gv-code.js, src/organisms/gv-documentation.js
**Issue**
n/a
to avoid this erreur only happen inside portal test 
=> fix: use lit instead lit-html to import classMap

src/policy-studio/gv-policy-studio.js, stories/policy-studio/gv-policy-studio.stories.js, stories/policy-studio/gv-policy-studio.test.js, stories/resources/apim-policies.json, stories/resources/schemas/rate-limit.json
**Issue**
https://github.com/gravitee-io/issues/issues/6614
Prefix description and condition with `common`
As we make a single form for the policy settings, the prefix allows to differentiate description and conditional from the policy's own fields.
📝 The conditional key is already defined in some policies for other aspects
=> Policy prefix common field

src/policy-studio/gv-flow-step.js
https://github.com/gravitee-io/issues/issues/6823
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-zvtwgblkwb.chromatic.com)
=> feat: improve conditional policy icon style

src/policy-studio/gv-policy-studio/gv-policy-studio.js
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-itbxqfwchv.chromatic.com)
=> fix(gv-policy-studio): ensure optional tabs order

package.json, yarn.lock
**Issue**
NA
For details see:
- https://snyk.io/blog/open-source-npm-packages-colors-faker
- https://github.com/Marak/colors.js/issues/285
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ttukbgaqqt.chromatic.com)
=> Pin `colors` version to avoid vulnerability

.storybook/main.js
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gxklgmpspg.chromatic.com)
=> chore: remove useless webpack config

src/mixins/input-element.js, src/mixins/keyboard-element.js, src/policy-studio/gv-policy-studio/gv-policy-studio.js
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-lgkfwhnolj.chromatic.com)
=> Fix policy studio keyboard conflict

src/lib/style.js
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-tnvrxeovgl.chromatic.com)
=> fix(style): mark defaultValue param as optional in getCssVar

src/lib/i18n.js
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-mbypstraei.chromatic.com)
=> fix(i18n): mark label param as optional in addTranslations method

src/organisms/gv-pagination/gv-pagination.ts
**Issue**
na
C'était sur que j'allais en oublier ! 🙄 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-kdazojjkzk.chromatic.com)
=> fix: explicitly add `.js` ending for each lit import

jest.config.js, src/index.js, src/lib/events.ts, src/organisms/gv-properties/gv-properties.js, src/organisms/gv-resources/gv-resources.js, src/organisms/gv-schema-form-control/gv-schema-form-control.js, src/organisms/gv-schema-form/gv-schema-form.js, src/organisms/gv-schema-form/gv-schema-form.test.js, src/policy-studio/gv-design/gv-design.js, src/policy-studio/gv-design/gv-design.stories.js, src/policy-studio/gv-design/gv-design.test.js, src/policy-studio/gv-design/index.ts, src/policy-studio/gv-policy-studio/gv-policy-studio.js, wc/gv-design.js
gravitee-io/issues#6893
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-zgpkvglpdm.chromatic.com)
=> feat(policy-studio): fork gv-policy-studio to gv-design

src/policy-studio/gv-design/gv-design.js
https://github.com/gravitee-io/issues/issues/6893
=> Revert "fix(gv-design): remove change event when user select step"

src/molecules/gv-code/gv-code.js, src/molecules/gv-code/gv-code.stories.js, src/molecules/gv-code/gv-code.test.js, src/molecules/gv-expression-language/gv-expression-language.test.js
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-jngknvsjhf.chromatic.com)
=> fix(gv-code): fix the value update

src/organisms/gv-schema-form/gv-schema-form.stories.js, testing/resources/schemas/resource-cache-redis.json
**Issue**
https://github.com/gravitee-io/issues/issues/7172
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ymaiaoefsx.chromatic.com)
=> Add story to test resource-cache-redis with gv-schema-form

src/organisms/gv-schema-form-array/gv-schema-form-array.js, src/organisms/gv-schema-form-control-object/gv-schema-form-control-object.js, src/organisms/gv-schema-form-control/gv-schema-form-control.js
Related to gravitee-io/issues#7022
See https://github.com/gravitee-io/gravitee-policy-data-logging-masking/pull/28 for 📸 screenshots
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gdhvfjsrvl.chromatic.com)
=> fix(gv-schema-form): remove useless compact attribute

package.json, yarn.lock
**Issue**
na
chore: bump highcharts & @highcharts/map-collection
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-manscrleuh.chromatic.com)
=> chore: bump highcharts & @highcharts/map-collection

src/lib/studio.js, src/policy-studio/gv-policy-studio/gv-policy-studio.test.js, testing/resources/am-definition.json, testing/resources/schemas/am.json
closes gravitee-io/issues#7470
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-pzcpqudfdg.chromatic.com)
=> feat: change and add icons for AM flows

src/organisms/gv-properties/gv-properties.js
**Issue**
https://github.com/gravitee-io/issues/issues/6065
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-hfdeahijvi.chromatic.com)
=> feat: reword API properties screen title

src/molecules/gv-table/gv-table.js
see https://github.com/gravitee-io/issues/issues/7241
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-jpqgzhztem.chromatic.com)
=> fix: properly setup confirm in tables

src/policy-studio/gv-design/gv-design.js, testing/resources/apim-policies.json
**Issue**
https://github.com/gravitee-io/issues/issues/8227
Wait for subcomponent to be rendered before interacting with it
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-masbgyvsms.chromatic.com)
=> gv-design: Wait for subcomponent to be rendered before interacting with it

src/molecules/gv-cron-editor/gv-cron-editor.js, src/molecules/gv-cron-editor/gv-cron-editor.stories.js, src/organisms/gv-tabs/gv-tabs.js
**Issue**
To reuse it in apim 
=> feat: add disabled state for gv-cron-editor

src/atoms/gv-input/gv-input.js, testing/resources/apim-resource-types.json
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-387
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-tzilcxwowx.chromatic.com)
=> fix(gv-input): dispatch submit event only on required icon

src/atoms/gv-date-picker/gv-date-picker.js
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-420
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-lcfwntvepy.chromatic.com)
=> fix(gv-date-picker): fix range time mode

src/atoms/gv-icon/gv-icon.js
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-467
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-qxjlgyutlx.chromatic.com)
=> fix(gv-icon): load icon only if has shape

src/atoms/gv-button/gv-button.js
**Issue**
https://github.com/gravitee-io/issues/issues/8677
https://gravitee.atlassian.net/browse/APIM-364
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-paypaazknd.chromatic.com)
=> fix(gv-button): remove useless css rule

src/organisms/gv-properties/gv-properties.js, src/organisms/gv-properties/gv-properties.stories.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-867
https://github.com/gravitee-io/issues/issues/7048
Handle page size update, previously the page size update wasn't linked to the pageSize property
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-wpondukhow.chromatic.com)
=> fix(gv-properties): handle page size update

src/charts/gv-chart-gauge-progress/gv-chart-gauge-progress.js, src/charts/gv-chart-gauge-progress/gv-chart-gauge-progress.stories.js, src/charts/gv-chart-gauge-progress/index.ts, src/index.js, src/mixins/chart-element.js
**Issue**
https://gravitee.atlassian.net/browse/COC-280
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gwenlfqxur.chromatic.com)
=> feat: add gv-chart-gauge-progress component

src/organisms/gv-properties/gv-properties.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-531
https://github.com/gravitee-io/issues/issues/8802
Emit change event on key input change
Currently only value input emit this event 🤷‍♂️ 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-yjuzjsutyf.chromatic.com)
=> fix: emit change event on key input change

src/charts/gv-chart-gauge-progress/gv-chart-gauge-progress.js, src/charts/gv-chart-gauge-progress/gv-chart-gauge-progress.stories.js
**Issue**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-wlxpifwptm.chromatic.com)
=> fix(gv-chart-gauge-progress): simplify component

src/charts/gv-chart-gauge-progress/gv-chart-gauge-progress.js, src/charts/gv-chart-gauge-progress/gv-chart-gauge-progress.stories.js
**Issue**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gkehzyvfxf.chromatic.com)
=> feat: improve customization of gv-chart-gauge-progress

src/lib/studio.js
closes AM-610
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-uhohahuorp.chromatic.com)
=> feat: better support AM Flow icons

src/policy-studio/gv-design/gv-design.js
**Issue**
https://gravitee.atlassian.net/browse/AM-1012
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-atgkzeuwts.chromatic.com)
=> feat: expose validate fn to force form validation

src/policy-studio/gv-design/gv-design.js
**Issue**
https://gravitee.atlassian.net/browse/AM-1012
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-jbwxqpjjya.chromatic.com)
=> fix: remove confirm state when policy changed or submitted

package.json, src/lib/text-format.js, yarn.lock
**Issue**
Needed for apim with Angular 14 and Angular CLI
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-mbfnvdrhcg.chromatic.com)
=> feat: bump asciidoctor to 3.0.2

src/lib/style.js, src/molecules/gv-plans/gv-plans.js, src/molecules/gv-tree/gv-tree.js
**Issue**
https://gravitee.atlassian.net/browse/APIM-3821
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-xqvwsurqqe.chromatic.com)
=> fix: improve a11y with custom gv-plans

src/molecules/gv-promote/gv-promote.js, src/molecules/gv-promote/gv-promote.stories.js
see https://gravitee.atlassian.net/browse/APIM-3892
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-znynlcqeym.chromatic.com)
=> fix: render markdown in gv-promote description

src/molecules/gv-row/gv-row.js, src/molecules/gv-row/gv-row.stories.js
see https://gravitee.atlassian.net/browse/APIM-3892
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-iotqaxvmia.chromatic.com)
=> fix: render markdown in gv-row description

src/atoms/gv-input/gv-input.js
https://gravitee.atlassian.net/browse/APIM-9162
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ubwuysaqkm.chromatic.com)
=> fix: APIM-9162: Dev portal - Application alert displays miss value after save
